name: Deploy de la pagina
on: 
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
    name: Checkout
    uses: actions/checkout@v2.3.1

    name: Deploy
    uses: jemesives/github-pages-deploy-action@4.1.1
    with:
      branch: gh-pages
      folder: . '\n' #C:\PYTHON\PYTHON- WEB\PYTHON-GIT