name: Deploy de la pagina
on:
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      name: Checkout
      uses: actions/checkout@v2.3.1

      name: Deploy
      uses: ROMERO-MARCOS/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: C:\PYTHON\PYTHON- WEB\PYTHON-GIT